name: Checks
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Checks
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 15

      - name: Install Dependencies
        run: npm i

      - name: Lint src
        run: npx eslint src/**
